"""Initial migration

Revision ID: a37f2419d88e
Revises:
Create Date: 2026-01-12 04:28:33.845189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a37f2419d88e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_uuid', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('last_checkin', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('management_ip', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('snmp_version', sa.Enum('v1', 'v2c', 'v3', name='snmp_version_enum'), nullable=False),
    sa.Column('snmp_community', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('discovery_source', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nmap_arguments', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('physical_address', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snmp_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Enum('v1', 'v2c', 'v3', name='snmp_version_enum'), nullable=False),
    sa.Column('community_string', sa.String(), nullable=True),
    sa.Column('v3_username', sa.String(), nullable=True),
    sa.Column('v3_auth_key', sa.String(), nullable=True),
    sa.Column('v3_priv_key', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arp_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('interface_name', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('if_index', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('Up', 'Down', 'Testing', name='interface_status_enum'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('vlan_mode', sa.Enum('Access', 'Trunk', 'General', name='vlan_mode_enum'), nullable=True),
    sa.Column('native_vlan', sa.Integer(), nullable=True),
    sa.Column('allowed_vlans', sa.String(), nullable=True),
    sa.Column('speed_bandwidth', sa.BigInteger(), nullable=True),
    sa.Column('mtu', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_targets',
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('network_cidr', sa.String(), nullable=False),
    sa.Column('snmp_profile_id', sa.Integer(), nullable=False),
    sa.Column('scan_profile_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['scan_profile_id'], ['scan_profiles.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['snmp_profile_id'], ['snmp_configs.id'], ),
    sa.PrimaryKeyConstraint('target_id')
    )
    op.create_table('vlans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('vlan_number', sa.Integer(), nullable=False),
    sa.Column('vlan_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mac_address_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('Static', 'Dynamic', name='mac_address_type_enum'), nullable=True),
    sa.ForeignKeyConstraint(['interface_id'], ['interfaces.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neighbors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_interface_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('remote_node_hostname', sa.String(), nullable=True),
    sa.Column('remote_interface_name', sa.String(), nullable=True),
    sa.Column('remote_mgmt_ip', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['local_interface_id'], ['interfaces.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routing_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('destination_cidr', sa.String(), nullable=False),
    sa.Column('next_hop', sa.String(), nullable=True),
    sa.Column('interface_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interface_id'], ['interfaces.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routing_tables')
    op.drop_table('neighbors')
    op.drop_table('mac_address_tables')
    op.drop_table('vlans')
    op.drop_table('scan_targets')
    op.drop_table('interfaces')
    op.drop_table('arp_tables')
    op.drop_table('snmp_configs')
    op.drop_table('sites')
    op.drop_table('scan_profiles')
    op.drop_table('nodes')
    op.drop_table('api_keys')
    op.drop_table('organizations')
    # ### end Alembic commands ###
